default_platform(:ios)

platform :ios do
  lane :projectA do
    xcodebuild(
      workspace: "SampleModularApp.xcworkspace",
      scheme: "ProjectA",
      configuration: "Debug"
    )
    # add actions here: https://docs.fastlane.tools/actions
  end

  lane :projectB do
    xcodebuild(
      workspace: "SampleModularApp.xcworkspace",
      scheme: "ProjectB",
      configuration: "Debug"
    )
    # add actions here: https://docs.fastlane.tools/actions
  end

  lane :projectC do
    xcodebuild(
      workspace: "SampleModularApp.xcworkspace",
      scheme: "ProjectC",
      configuration: "Debug"
    )
    # add actions here: https://docs.fastlane.tools/actions
  end
end
